export const Images = {
  CommonBG: require("../Assets/Image/BG.png"),
  splash_screens: require("../Assets/Image/GetStart/splash_screens.png"),

  Logo: require("../Assets/Image/Profile/profiles.jpeg"),
  check: require("../Assets/Image/Login/check.png"),
  uncheck: require("../Assets/Image/Login/uncheck.png"),
  tick: require("../Assets/Image/Login/tick.png"),
  mobilephone: require("../Assets/Image/Login/mobilephone.png"),

  Boardingcards: require("../Assets/Image/GetStart/Boardingcards.png"),
  Boardingcards2: require("../Assets/Image/GetStart/Boardingcards2.png"),
  Tradelikeyoudate: require("../Assets/Image/GetStart/Tradelikeyoudate.png"),
  SwipeToLeftIcon: require("../Assets/Image/GetStart/SwipeToLeftIcon.png"),
  PoweredByTopBrokers: require("../Assets/Image/GetStart/PoweredByTopBrokers.png"),
  chat: require("../Assets/Image/GetStart/chat.png"),
  home: require("../Assets/Image/GetStart/home.png"),
  profile: require("../Assets/Image/GetStart/profile.png"),
  profilePic: require("../Assets/Image/GetStart/profilePic.png"),
  bin: require("../Assets/Image/GetStart/bin.png"),

  arrowLeft: require("../Assets/Image/Components/arrowLeft.png"),
  roundBackgorundBlur: require("../Assets/Image/Components/roundBackgorundBlur.png"),
  search: require("../Assets/Image/Components/search.png"),
  notificationIcon: require("../Assets/Image/Components/notificationIcon.png"),
  rupees: require("../Assets/Image/Components/rupees.png"),
  threeDotIcon: require("../Assets/Image/Components/threeDotIcon.png"),
  rightArrow: require("../Assets/Image/Components/right-arrow.png"),
  edit: require("../Assets/Image/Components/edit.png"),
  editFrame: require("../Assets/Image/Components/EditFrame.png"),

  tabMainIcon: require("../Assets/Image/TabBar/tabMainIcon.png"),
  invest: require("../Assets/Image/TabBar/invest.png"),
  investFilled: require("../Assets/Image/TabBar/investFilled.png"),
  market: require("../Assets/Image/TabBar/market.png"),
  marketFilled: require("../Assets/Image/TabBar/marketFilled.png"),
  portfolio: require("../Assets/Image/TabBar/portfolio.png"),
  portfolioFilled: require("../Assets/Image/TabBar/portfolioFilled.png"),
  tabHomeFilled: require("../Assets/Image/TabBar/tabHomeFilled.png"),
  tabHome: require("../Assets/Image/TabBar/tabHome.png"),

  DummyImage: require("../Assets/Image/AINFY/PortImage.png"),
  addFunds: require("../Assets/Image/AINFY/addFunds.png"),
  Withdraw: require("../Assets/Image/AINFY/Withdraw.png"),

  profileBackground: require("../Assets/Image/Profile/profile-background.png"),
  userAvatar: require("../Assets/Image/Profile/avatar.png"),
  addBroker: require("../Assets/Image/Profile/add-broker.png"),
  reward: require("../Assets/Image/Profile/reward.png"),
  invite: require("../Assets/Image/Profile/invite.png"),
  inr: require("../Assets/Image/Profile/price.png"),
  order: require("../Assets/Image/Profile/order.png"),
  BackButton: require("../Assets/Image/Profile/BackButton.png"),
  additem: require("../Assets/Image/Profile/additem.png"),
  Deal: require('../Assets/Image/RiseList/Deal.png'),
  gallery: require('../Assets/Image/RiseList/gallery.png'),
  message: require('../Assets/Image/RiseList/message.png'),
  call: require('../Assets/Image/RiseList/Phone.png'),
};
